# Generated by Django 5.1.3 on 2024-11-23 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bankrec", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transactionentry",
            old_name="payment_method",
            new_name="transaction_type",
        ),
    ]
